inherit_from:
  - https://dev.k.io/rubocop/rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - Rakefile
    - "bin/**/*"

# Always use double quotes
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 50
